module.exports = {
    router:{
        linkActiveClass:'active',
        extendRoutes(router,resolve){
            router.splice(0)
            router.push(...[
                {
                    path:'/',
                    component:resolve(__dirname,'pages/layout'),
                    children:[
                        {
                            path:'',
                            name:'home',
                            component:resolve(__dirname,'pages/home')
                        },
                        {
                            path:'/login',
                            name:'login',
                            component:resolve(__dirname,'pages/login')
                        },
                        {
                            path:'/register',
                            name:'register',
                            component:resolve(__dirname,'pages/login')
                        },
                        {
                            path:'/profile/:username',
                            name:'profile',
                            component:resolve(__dirname,'pages/profile')
                        },
                        {
                            path:'/setting',
                            name:'setting',
                            component:resolve(__dirname,'pages/setting')
                        },
                        {
                            path:'/editor',
                            name:'editor',
                            component:resolve(__dirname,'pages/editor')
                        },
                        {
                            path:'/article/:slug',
                            name:'article',
                            component:resolve(__dirname,'pages/article')
                        },
                        {
                            path:'/other',
                            name:'other',
                            component:resolve(__dirname,'pages')
                        },
                    ]
                }
            ])
        }
    },
    plugins:[
        '~/plugins/request.js',
        '~/plugins/dayjs.js'
    ]
}
